using System.Buffers.Text;
using BlindPaste.Api.Options;
using BlindPaste.Api.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.Extensions.Options;

namespace BlindPaste.Api.Controllers;

/// Create and read pastes.
///
/// The server treats `payload` as opaque: it checks that the string is base64url and
/// within the size limit, and nothing else. It deliberately does not know the header
/// layout or the minimum length implied by it, because the moment it did, changing a
/// crypto parameter in the browser would become a coordinated deployment instead of
/// the frontend-only change web/src/lib/payload.ts promises it is.
[ApiController]
[Route("api/[controller]")]
public class PastesController(PasteStore store, IOptions<PasteOptions> options) : ControllerBase
{
    public record CreatePasteRequest(string? Payload, int? ExpiresInSeconds, bool BurnAfterReading);

    public record CreatePasteResponse(string Id, DateTimeOffset ExpiresAt, bool BurnAfterReading);

    public record PasteResponse(string Payload, DateTimeOffset ExpiresAt, bool BurnAfterReading);

    [HttpPost]
    [EnableRateLimiting(RateLimiterPolicies.CreatePaste)]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests)]
    public async Task<ActionResult<CreatePasteResponse>> Create(
        CreatePasteRequest request,
        CancellationToken cancellationToken)
    {
        var settings = options.Value;

        if (string.IsNullOrEmpty(request.Payload))
        {
            ModelState.AddModelError(nameof(request.Payload), "A payload is required.");
            return ValidationProblem(ModelState);
        }

        if (request.Payload.Length > settings.MaxPayloadCharacters)
        {
            ModelState.AddModelError(
                nameof(request.Payload),
                $"Payload is {request.Payload.Length} characters, over the {settings.MaxPayloadCharacters} limit.");
            return ValidationProblem(ModelState);
        }

        if (!Base64Url.IsValid(request.Payload))
        {
            ModelState.AddModelError(nameof(request.Payload), "Payload is not valid base64url.");
            return ValidationProblem(ModelState);
        }

        var expiry = request.ExpiresInSeconds is { } seconds
            ? TimeSpan.FromSeconds(seconds)
            : settings.DefaultExpiry;

        // Rejected rather than clamped: storing a paste for a different span than the
        // one asked for is worse than refusing, because the caller would never know.
        if (expiry < settings.MinExpiry || expiry > settings.MaxExpiry)
        {
            ModelState.AddModelError(
                nameof(request.ExpiresInSeconds),
                $"Expiry must be between {settings.MinExpiry.TotalSeconds} and {settings.MaxExpiry.TotalSeconds} seconds.");
            return ValidationProblem(ModelState);
        }

        var paste = await store.CreateAsync(
            request.Payload,
            request.BurnAfterReading,
            DateTimeOffset.UtcNow + expiry,
            cancellationToken);

        // The Location path is written out rather than generated by CreatedAtAction on
        // purpose. Program.cs sets RouteOptions.LowercaseUrls, which lowercases the
        // whole generated path — route values included — and a paste id is
        // case-sensitive base64url, so a generated Location points at an id that does
        // not exist. Keep this literal, or verify the header still resolves.
        return Created($"/api/pastes/{paste.Id}", new CreatePasteResponse(paste.Id, paste.ExpiresAt, paste.BurnAfterReading));
    }

    [HttpGet("{id}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<PasteResponse>> Get(string id, CancellationToken cancellationToken)
    {
        var paste = await store.ReadOnceAsync(id, cancellationToken);

        // Missing, expired, and already-burned are one response on purpose. Telling
        // them apart would confirm to someone guessing ids that a paste had existed.
        if (paste is null)
        {
            return NotFound();
        }

        // Ciphertext is useless without the key, but a burn-after-reading paste that a
        // proxy or the browser kept a copy of is no longer burned.
        Response.Headers.CacheControl = "no-store";

        return Ok(new PasteResponse(paste.Payload, paste.ExpiresAt, paste.BurnAfterReading));
    }
}
