using BlindPaste.Api.Entities;
using Microsoft.EntityFrameworkCore;

namespace BlindPaste.Api.Persistence;

/// Maps to the Liquibase-managed schema. EF never owns migrations here — the model
/// mirrors what the changesets create, and `dotnet ef migrations add` must never be
/// run against this context. Column names come from the snake_case convention;
/// tables are set explicitly.
///
/// Tracking is off by default: reads never need it, and the two writes that exist —
/// inserting a paste and deleting one — do not depend on it either. Add() tracks the
/// entity it is handed regardless, and deletes go through ExecuteDelete, which issues
/// SQL directly. Schema changes go through a new changeset in
/// database/changelog/changesets/.
public class BlindPasteDbContext(DbContextOptions<BlindPasteDbContext> options) : DbContext(options)
{
    public DbSet<Paste> Pastes => Set<Paste>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSnakeCaseNamingConvention()
            .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Paste>(e =>
        {
            e.ToTable("paste");
            e.HasKey(x => x.Id);

            // The id is generated by PasteStore, not the database — EF would otherwise
            // assume a store-generated value for a string key it did not see set.
            e.Property(x => x.Id).ValueGeneratedNever();

            e.HasIndex(x => x.ExpiresAt).HasDatabaseName("ix_paste_expires_at");
        });
    }
}
