namespace BlindPaste.Api.Entities;

public class Paste
{
    /// 22 base64url characters — 128 bits of randomness. Generated by PasteStore.
    public required string Id { get; set; }

    /// The browser's opaque payload token. Never parsed here.
    public required string Payload { get; set; }

    public bool BurnAfterReading { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    /// Null means the paste never expires
    public DateTimeOffset? ExpiresAt { get; set; }
}
