namespace BlindPaste.Api.Entities;

/// Mirrors the `paste` table created by Liquibase changeset 0002_create_paste.sql.
/// Liquibase owns this shape — if the changeset changes, update this to match.
///
/// A row is written once and then only read or deleted; nothing updates a paste.
/// PasteStore depends on that when it serves a burn-after-reading paste.
public class Paste
{
    /// 22 base64url characters — 128 bits of randomness. Generated by PasteStore.
    public required string Id { get; set; }

    /// The browser's opaque payload token. Never parsed here.
    public required string Payload { get; set; }

    public bool BurnAfterReading { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset ExpiresAt { get; set; }
}
